Added search fields to admin's teachers view, added more fields to…
sio2project/oioioi pull request #138
Opened 2023-01-16 20:58 UTC by Aszanat

… show on teachers list (still in admin's view).

2023-02-27 10:49 UTC, twalen commented on oioioi/teachers/models.py
> +    join_date = models.DateField(auto_now_add=True)
migration is needed!

2023-02-27 10:50 UTC, twalen requested changes
Please add a migration for new model field

2023-03-01 22:01 UTC, A-dead-pixel commented
I think you added ``extra/easy-install/.venv`` and ``oioioi.log`` by mistake to the last commit @Aszanat. Patterns like ``**/.venv*/`` and ``**/oioioi.log`` (or maybe ``**/*.log``?) should probably be added to ``.gitignore``.

2023-03-06 08:52 UTC, twalen commented on oioioi/teachers/admin.py
> +    teacher_login.short_description = _("Userame")
Userame -> Username

2023-03-06 08:54 UTC, twalen requested changes
Looks good. Please fix typo and we can merge it.

2023-03-07 14:56 UTC, merged