Fix replacing files in problem package (#148)
sio2project/oioioi pull request #149
Opened 2023-02-11 20:02 UTC by A-dead-pixel

Resolves #148.

We don't need to manually truncate as that is done by "w" during open().

2023-03-06 09:11 UTC, twalen commented on oioioi/problems/problem_site.py
> +    with open(file_path, "wb") as original_file:
Nice catch! But I think that test case for uploading single file should be added. It seems that right now it has not been covered by tests.

2023-03-06 09:12 UTC, twalen requested changes
Please add regression tests and we can merge it.

2023-06-04 11:55 UTC, A-dead-pixel commented
I added the test, but in the meantime accidentaly discovered that this still does not work for non-superusers.

2023-06-15 14:33 UTC, twalen approved these changes

2023-06-15 14:33 UTC, merged