Issue #206 solve: Autocomplete search fields
sio2project/oioioi pull request #217
Opened 2023-05-25 16:44 UTC by Aszanat

2023-05-25 20:05 UTC, A-dead-pixel commented
I would also add autocompletion to the form for adding new participants to a contest.
Additionally, I don't think we should filter out non-teachers, as they are often non-existent (like on sio2.mimuw, basing on the lack of "Request teacher account" in the user menu) and even if enabled, probably not all contest rights (especially observer ones) would be given to teachers only.

PS.
I think you accidentally deleted ``.gitignore``.

2023-05-29 12:11 UTC, twalen commented on .gitignore
please remove this file from PR

2023-05-29 12:12 UTC, twalen commented on oioioi/contests/views.py
> +def get_teacher_names(request):
this view needs to be protected (i.e. only for admins)

2023-06-01 14:48 UTC, twalen requested changes
remove .gitignore
fix permission issues

2026-09-16 14:32 UTC, twalen commented
closing due to stale Draft status

2026-09-16 14:32 UTC, closed without merging