Change PARegistration form (#293)
sio2project/oioioi pull request #298
Opened 2023-12-04 09:57 UTC by zggf-zggf

* Add checkbox to PARegistrationForm

* Change PARegistration model to allow null values

* Add logic to verify address only when needed

2023-12-04 14:04 UTC, MasloMaslane requested changes
Also, could you add javascript that will disable/enable address and t-shirt fields when the checkbox is toggled?

2023-12-06 13:54 UTC, twalen commented on oioioi/pa/forms.py
> +    eligible_for_prizes.label = _("I want to be eligible for prizes.")
+1 from me

2023-12-20 15:53 UTC, twalen approved these changes
OK

2023-12-20 15:57 UTC, twalen approved these changes

2023-12-20 15:58 UTC, MasloMaslane approved these changes

2023-12-20 15:58 UTC, merged