SIO-2452 Wbudowany edytor kodu
sio2project/oioioi pull request #60
Opened 2022-04-21 16:04 UTC by andr729

2022-04-21 16:18 UTC, tudny reviewed
First impression comments, not a proper review.

2022-04-27 10:01 UTC, twalen commented on oioioi/base/models.py
> +        _("Używaj edytora kodu"),
English text should be used here.

2022-04-27 10:02 UTC, twalen commented on .vscode/settings.json
> +{
+1 for adding .vscode to .gitignore

2022-04-27 10:04 UTC, twalen commented on oioioi/base/migrations/0003_auto_20220420_1236_squashed_0004_rename_preferred_language_userpreferences_language.py
> +        migrations.RemoveField(
this looks strange, why we need to remove field and then add it again?

2022-05-16 09:21 UTC, twalen requested changes
please fix small issues and we can merge it

2022-05-16 09:21 UTC, twalen commented on oioioi/base/templates/widgets/aceeditor.html
> +                //set_mode(editor, "c_cpp");
this can be removed

2022-05-16 09:21 UTC, twalen commented on oioioi/contests/views.py
> +
why new line?

2022-05-16 11:03 UTC, twalen approved these changes

2022-05-16 11:04 UTC, merged

2022-07-21 07:14 UTC, kostca commented
If you turn on "Enable editor" in your profile settings, you are not able to use the editor in the problemset, as there's another toggle for the contests.